apiVersion: v1
kind: Service
metadata:
    name: wil-playground-svc
    namespace: dev
spec:
    selector:
        app: playground
    ports:
        - name: playground-svc-port
          protocol: TCP
          port: 8888
          targetPort: http-playground-svc
