apiVersion: v1
kind: Service
metadata:
    name: wil-playground-svc
spec:
    selector:
        app.kubernetes.io/name: playground
    ports:
        - name: app-svc-port
          protocol: TCP
          port: 8888
          targetPort: http-app-svc
